version: '3.8'
services:

  db:
    image: docker.io/library/postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}

  test_db:
    image: docker.io/library/postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}

  test:
    build: .
    volumes:
      - .:/app
    depends_on:
      - web
      - test_db
      - redis
    environment:
      DATABASE_URL: postgresql+asyncpg://${TEST_DB_USER}:${TEST_DB_PASSWORD}@test_db/${TEST_DB_NAME}

  redis:
    image: docker.io/library/redis
    ports:
      - 6379:6379

  rabbitmq:
    image: docker.io/library/rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  celery_worker:
    build: .
    command: ["celery", "-A", "app.celery_worker", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - web
      - db
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}

  celery_beat:
    build: .
    command: ["celery", "-A", "app.celery_worker", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - web
      - db
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
